# Generated by Django 4.2.18 on 2025-02-25 07:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BestMoments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Текст")),
                (
                    "link_moments",
                    models.URLField(
                        blank=True, null=True, verbose_name="Лучшие моменты"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Лучшие моменты",
                "verbose_name_plural": "Лучшие моменты",
            },
        ),
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="management/",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководство",
                "verbose_name_plural": "Руководство",
            },
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_match",
                    models.DateField(blank=True, null=True, verbose_name="Дата матча"),
                ),
                (
                    "home_goals",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Голы хозяев"
                    ),
                ),
                (
                    "away_goals",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Голы гостей"
                    ),
                ),
                (
                    "stadium",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Стадион"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Не начался", "Не начался"),
                            ("В процессе", "В процессе"),
                            ("Закончен", "Закончен"),
                        ],
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матч",
                "verbose_name_plural": "Матчи",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Изображение",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="players/", verbose_name="Фото"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Вратарь", "Goalkeeper"),
                            ("Защитник", "Defender"),
                            ("Полузащитник", "Midfielder"),
                            ("Нападающий", "Forward"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(blank=True, null=True, verbose_name="Номер"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="Рост"),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="Вес"),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Национальность",
                    ),
                ),
                (
                    "goals",
                    models.IntegerField(blank=True, null=True, verbose_name="Голы"),
                ),
                (
                    "assists",
                    models.IntegerField(blank=True, null=True, verbose_name="Пасы"),
                ),
                (
                    "yellow_cards",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Желтые карточки"
                    ),
                ),
                (
                    "red_cards",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Красные карточки"
                    ),
                ),
                (
                    "games",
                    models.IntegerField(blank=True, null=True, verbose_name="Игры"),
                ),
                (
                    "minutes",
                    models.IntegerField(blank=True, null=True, verbose_name="Минуты"),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(max_length=9, unique=True, verbose_name="Сезон"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Текущий"),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
            ],
            options={
                "verbose_name": "Сезон",
                "verbose_name_plural": "Сезоны",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_logo/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_favicon/",
                        verbose_name="Фавикон",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram_link",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "tiktok_link",
                    models.URLField(blank=True, null=True, verbose_name="TikTok"),
                ),
                (
                    "youtube_link",
                    models.URLField(blank=True, null=True, verbose_name="YouTube"),
                ),
                (
                    "copy_right",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Копирайт"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название команды"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teams/",
                        verbose_name="Логотип команды",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "stadium",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Стадион"
                    ),
                ),
                (
                    "coach",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Тренер"
                    ),
                ),
                (
                    "founded_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год основания"
                    ),
                ),
                (
                    "wins",
                    models.IntegerField(blank=True, null=True, verbose_name="Побед"),
                ),
                (
                    "draws",
                    models.IntegerField(blank=True, null=True, verbose_name="Ничьих"),
                ),
                (
                    "losses",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Поражений"
                    ),
                ),
                (
                    "goals_scored",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Забитых мячей"
                    ),
                ),
                (
                    "goals_conceded",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Пропущенных мячей"
                    ),
                ),
                (
                    "clean_sheets",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Сухих матчей"
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название турнира"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tournaments/",
                        verbose_name="Логотип турнира",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Турнир",
                "verbose_name_plural": "Турниры",
            },
        ),
        migrations.CreateModel(
            name="StaticticsPlayerSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goals", models.IntegerField(verbose_name="Голы")),
                ("assists", models.IntegerField(verbose_name="Пасы")),
                ("yellow_cards", models.IntegerField(verbose_name="Желтые карточки")),
                ("red_cards", models.IntegerField(verbose_name="Красные карточки")),
                ("games", models.IntegerField(verbose_name="Игры")),
                ("minutes", models.IntegerField(verbose_name="Минуты")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.players",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="core.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика игрока за сезон",
                "verbose_name_plural": "Статистика игроков за сезон",
            },
        ),
        migrations.CreateModel(
            name="Standings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games", models.IntegerField(verbose_name="Игры")),
                ("wins", models.IntegerField(verbose_name="Победы")),
                ("draws", models.IntegerField(verbose_name="Ничьи")),
                ("losses", models.IntegerField(verbose_name="Поражения")),
                ("goals_scored", models.IntegerField(verbose_name="Забитые голы")),
                (
                    "goals_conceded",
                    models.IntegerField(verbose_name="Пропущенные голы"),
                ),
                (
                    "goals_difference",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Разница голов"
                    ),
                ),
                ("points", models.IntegerField(verbose_name="Очки")),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teams",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="core.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Турнирная таблица",
                "verbose_name_plural": "Турнирные таблицы",
            },
        ),
        migrations.CreateModel(
            name="SeasonAwards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_coach",
                        to="core.management",
                        verbose_name="Лучший тренер",
                    ),
                ),
                (
                    "best_goalkeeper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_goalkeeper",
                        to="core.players",
                        verbose_name="Лучший вратарь",
                    ),
                ),
                (
                    "best_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_player",
                        to="core.players",
                        verbose_name="Лучший игрок сезона",
                    ),
                ),
                (
                    "best_scorer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_scorer",
                        to="core.players",
                        verbose_name="Лучший бомбардир",
                    ),
                ),
                (
                    "best_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_team",
                        to="core.teams",
                        verbose_name="Лучшая команда",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="core.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награды сезона",
                "verbose_name_plural": "Награды сезона",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(verbose_name="Номер тура"),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="core.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тур",
                "verbose_name_plural": "Туры",
                "ordering": ["round_number"],
            },
        ),
        migrations.AddField(
            model_name="players",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.teams",
                verbose_name="Команда",
            ),
        ),
        migrations.CreateModel(
            name="MatchLineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_starting",
                    models.BooleanField(
                        default=False, verbose_name="В стартовом составе"
                    ),
                ),
                (
                    "is_substitute",
                    models.BooleanField(default=False, verbose_name="Запасной"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="core.matches",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="core.players",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="core.teams",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав матча",
                "verbose_name_plural": "Составы матчей",
            },
        ),
        migrations.AddField(
            model_name="matches",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="core.teams",
                verbose_name="Гости",
            ),
        ),
        migrations.AddField(
            model_name="matches",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="core.teams",
                verbose_name="Хозяева",
            ),
        ),
        migrations.AddField(
            model_name="matches",
            name="mvp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.players",
                verbose_name="Лучший игрок",
            ),
        ),
        migrations.AddField(
            model_name="matches",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="core.round",
                verbose_name="Тур",
            ),
        ),
        migrations.AddField(
            model_name="matches",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="core.season",
                verbose_name="Сезон",
            ),
        ),
        migrations.AddField(
            model_name="matches",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="core.tournament",
                verbose_name="Турнир",
            ),
        ),
        migrations.AddField(
            model_name="management",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.teams",
                verbose_name="Команда",
            ),
        ),
        migrations.CreateModel(
            name="EventsMathes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("Гол", "Goal"),
                            ("Пас", "Assist"),
                            ("Желтая карточка", "Yellow Card"),
                            ("Красная карточка", "Red Card"),
                            ("Незабитый пенальти", "No Penalty"),
                            ("Забитый пенальти", "Penalty"),
                            ("Замена", "Substitution"),
                            ("Автогол", "Auto Goal"),
                            ("Травма", "Injury"),
                        ],
                        max_length=100,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "time",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(130),
                        ],
                        verbose_name="Минута матча",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.matches",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.players",
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
