# Generated by Django 4.2.18 on 2025-01-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Вратарь", "Goalkeeper"),
                    ("Защитник", "Defender"),
                    ("Полузащитник", "Midfielder"),
                    ("Нападающий", "Forward"),
                ],
                max_length=100,
                null=True,
                verbose_name="Позиция",
            ),
        ),
    ]
