# Generated by Django 4.2.18 on 2025-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_standings_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestMoments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Текст")),
                (
                    "link_moments",
                    models.URLField(
                        blank=True, null=True, verbose_name="Лучшие моменты"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Лучшие моменты",
                "verbose_name_plural": "Лучшие моменты",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Изображение",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_logo/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_favicon/",
                        verbose_name="Фавикон",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram_link",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "tiktok_link",
                    models.URLField(blank=True, null=True, verbose_name="TikTok"),
                ),
                (
                    "youtube_link",
                    models.URLField(blank=True, null=True, verbose_name="YouTube"),
                ),
                (
                    "copy_right",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Копирайт"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
