# Generated by Django 4.2.18 on 2025-02-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_season_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="year",
            field=models.IntegerField(unique=True, verbose_name="Сезон"),
        ),
    ]
