# Generated by Django 4.2.18 on 2025-03-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_season_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Спонсор")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sponsor_logo/",
                        verbose_name="Фото спонсора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спонсор",
                "verbose_name_plural": "Спонсоры",
            },
        ),
    ]
