# Generated by Django 4.2.18 on 2025-03-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="matches",
            name="documents",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/", verbose_name="Документы"
            ),
        ),
    ]
