# Generated by Django 4.2.18 on 2025-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_matches_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(verbose_name="О нас")),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="Документы",
                    ),
                ),
                ("management", models.TextField(verbose_name="Руководство")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "facebook_link",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram_link",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "tiktok_link",
                    models.URLField(blank=True, null=True, verbose_name="TikTok"),
                ),
                (
                    "youtube_link",
                    models.URLField(blank=True, null=True, verbose_name="YouTube"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="judges/", verbose_name="Фото"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="teams",
            name="clean_sheets",
        ),
        migrations.RemoveField(
            model_name="teams",
            name="draws",
        ),
        migrations.RemoveField(
            model_name="teams",
            name="goals_conceded",
        ),
        migrations.RemoveField(
            model_name="teams",
            name="goals_scored",
        ),
        migrations.RemoveField(
            model_name="teams",
            name="losses",
        ),
        migrations.RemoveField(
            model_name="teams",
            name="wins",
        ),
    ]
