# Generated by Django 4.2.18 on 2025-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_companyinfo_judge_remove_teams_clean_sheets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matches",
            name="time_match",
            field=models.TimeField(blank=True, null=True, verbose_name="Время матча"),
        ),
    ]
