# Generated by Django 4.2.18 on 2025-03-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_matches_time_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stadium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название стадиона"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("capacity", models.IntegerField(verbose_name="Вместимость")),
            ],
            options={
                "verbose_name": "Стадион",
                "verbose_name_plural": "Стадионы",
            },
        ),
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="news/", verbose_name="Изображение"),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение новости",
                "verbose_name_plural": "Изображения новостей",
            },
        ),
    ]
