# Generated by Django 4.2.18 on 2025-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_stadium_remove_news_image_newsimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("file", models.FileField(upload_to="documents/", verbose_name="Файл")),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="ManegementKfl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="management/",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководство",
                "verbose_name_plural": "Руководство",
            },
        ),
        migrations.AlterModelOptions(
            name="companyinfo",
            options={
                "verbose_name": "Информация о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="address",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="email",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="facebook_link",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="instagram_link",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="management",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="tiktok_link",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="youtube_link",
        ),
    ]
