# Generated by Django 4.2.18 on 2025-03-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_document_manegementkfl_alter_companyinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="judge",
            options={"verbose_name": "Судья", "verbose_name_plural": "Судьи"},
        ),
        migrations.AlterModelOptions(
            name="management",
            options={
                "verbose_name": "Руководство команды",
                "verbose_name_plural": "Руководство команды",
            },
        ),
        migrations.AlterField(
            model_name="staticticsplayerseason",
            name="games",
            field=models.IntegerField(blank=True, null=True, verbose_name="Игры"),
        ),
        migrations.AlterField(
            model_name="staticticsplayerseason",
            name="minutes",
            field=models.IntegerField(blank=True, null=True, verbose_name="Минуты"),
        ),
    ]
