# Generated by Django 4.2.18 on 2025-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_judge_options_alter_management_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matches",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Не начался", "Не начался"),
                    ("В процессе", "В процессе"),
                    ("Закончен", "Закончен"),
                ],
                default="Не начался",
                max_length=100,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
