# Generated by Django 4.2.18 on 2025-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_matches_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="matches",
            name="technical_defeat",
            field=models.BooleanField(
                default=False, verbose_name="Техническое поражение"
            ),
        ),
    ]
