# Generated by Django 4.2.18 on 2025-03-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_matches_technical_defeat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matches",
            name="stadium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="core.stadium",
                verbose_name="Стадион",
            ),
        ),
    ]
