# Generated by Django 4.2.18 on 2025-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_matches_stadium"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="adress",
            field=models.CharField(blank=True, null=True, verbose_name="Адрес"),
        ),
    ]
